// AUTO-GENERATED by scripts/codegen-ts.mjs from /protocol/schema/.
// DO NOT EDIT BY HAND. Edit the JSON Schema and run `npm run protocol:gen`.

/* eslint-disable */
/* tslint:disable */

// ───────────────────── envelope.schema.json ─────────────────────

/**
 * Top-level wrapper for any wire message. The receiver validates this shape first, then validates `payload` against the schema selected by `kind`.
 */
export interface Envelope {
  /**
   * MAJOR.MINOR — receivers refuse mismatched majors during the client-ready / bot-ready handshake.
   */
  protocol_version: string;
  /**
   * Selects which payload schema to apply.
   */
  kind: 'harness_event' | 'harness_command' | 'server_message';
  /**
   * Globally unique message id (e.g. ULID).
   */
  id: string;
  /**
   * ISO-8601 UTC timestamp from the sender.
   */
  timestamp: string;
  /**
   * Per-session HMAC token. Required on every message except the initial pairing exchange.
   */
  session_token?: string;
  /**
   * The kind-specific payload. Validated separately by the receiver.
   */
  payload: {
    [k: string]: unknown;
  };
}

// ───────────────────── harness-command.schema.json ─────────────────────

/**
 * Discriminated union of commands sent from the cloud orchestrator to the Mac session-host daemon. The daemon's command allowlist enforces that only these three kinds are accepted — anything else is rejected and audit-logged. Only user-initiated input (voice or typed) ever produces a submit_with_steer or cancel; background events route through the registry instead.
 */
export type HarnessCommand = SubmitText | SubmitWithSteer | Cancel;
export type SubmitText = Common & {
  kind: 'submit_text';
  payload: {
    text: string;
  };
};
export type SubmitWithSteer = Common & {
  kind: 'submit_with_steer';
  payload: {
    text: string;
    /**
     * The in-flight turn this command preempts.
     */
    cancels_correlation_id: string;
  };
};
export type Cancel = Common & {
  kind: 'cancel';
  payload: {
    /**
     * The in-flight turn to cancel.
     */
    target_correlation_id: string;
  };
};

export interface Common {
  /**
   * Unique ID for this turn. Events emitted while executing this command carry the same correlation_id.
   */
  correlation_id: string;
  /**
   * Harness target, e.g. 'claude-code', 'pi', 'hermes'.
   */
  target: string;
}

// ───────────────────── harness-event.schema.json ─────────────────────

/**
 * Two-tier discriminated union of events emitted by harness adapters back to the orchestrator. Tier 1 = canonical cross-provider events. Tier 2 = provider_event envelope for everything provider-specific. Adapters never silently drop wire events; anything that doesn't map to Tier 1 emits as Tier 2.
 */
export type HarnessEvent =
  | SessionInit
  | TextDelta
  | ReasoningDelta
  | AssistantMessage
  | ToolLifecycle
  | SessionEnd
  | ErrorEvent
  | CancelConfirmed
  | ProviderEvent;
export type SessionInit = Common & {
  type: 'session_init';
  session_id?: string;
  tools?: string[];
  model?: string;
};
export type TextDelta = Common & {
  type: 'text_delta';
  text: string;
};
export type ReasoningDelta = Common & {
  type: 'reasoning_delta';
  text: string;
};
export type AssistantMessage = Common & {
  type: 'assistant_message';
  text: string;
};
export type ToolLifecycle = Common & {
  type: 'tool_lifecycle';
  phase: 'start' | 'progress' | 'complete';
  name: string;
  tool_use_id?: string;
  /**
   * Tool input (provider-specific shape).
   */
  input?: {
    [k: string]: unknown;
  };
  /**
   * Tool result (provider-specific shape). Only present when phase=='complete'.
   */
  result?: {
    [k: string]: unknown;
  };
};
export type SessionEnd = Common & {
  type: 'session_end';
  subtype: 'success' | 'error';
  result?: string;
  cost_usd?: number;
  usage?: {
    input?: number;
    output?: number;
    [k: string]: unknown;
  };
};
export type ErrorEvent = Common & {
  type: 'error';
  message: string;
};
export type CancelConfirmed = Common & {
  type: 'cancel_confirmed';
};
export type ProviderEvent = Common & {
  type: 'provider_event';
  /**
   * Provider namespace, e.g. 'claude-code', 'hermes', 'pi', 'overwatch' for daemon-internal sources.
   */
  provider: string;
  /**
   * Provider-scoped event kind. Combined with provider as 'provider/kind' for HARNESS_EVENT_CONFIGS lookup.
   */
  kind: string;
  /**
   * Provider-specific payload. Untyped at the protocol layer; consumers parse based on registry config.
   */
  payload?: {
    [k: string]: unknown;
  };
};

export interface Common {
  /**
   * ID of the turn this event belongs to. Set by the daemon when dispatching the originating command.
   */
  correlation_id: string;
  /**
   * Harness target identifier, e.g. 'claude-code', 'pi', 'hermes'.
   */
  target: string;
  /**
   * Verbatim wire payload from the harness, for debugging and the catch-all logger. Passthrough; not validated.
   */
  raw?: {
    [k: string]: unknown;
  };
}

// ───────────────────── server-message.schema.json ─────────────────────

/**
 * Typed envelopes for non-RTVI events flowing between the cloud orchestrator and the mobile client over the Daily WebRTC data channel. Sits alongside the RTVI standard messages (user-transcription, bot-llm-text, etc.) which are not redefined here.
 */
export type ServerMessage =
  | UserText
  | HarnessEventForUI
  | HarnessStateSnapshot
  | InterruptIntent
  | Notification
  | ErrorResponse;

/**
 * User-typed text from mobile InputBar. Handled by the orchestrator's HarnessBridgeProcessor identically to a voice transcript: in-flight check, then submit_text or submit_with_steer.
 */
export interface UserText {
  type: 'user_text';
  text: string;
}
/**
 * Wraps a HarnessEvent the orchestrator's registry routed to voice_action='ui-only'. Mobile renders as transcript pill / status row.
 */
export interface HarnessEventForUI {
  type: 'harness_event';
  /**
   * Full HarnessEvent payload (see harness-event.schema.json).
   */
  event: {};
}
/**
 * Periodic state snapshot for the mobile UI to derive 'is the harness busy' indicators.
 */
export interface HarnessStateSnapshot {
  type: 'harness_state';
  active_target: string;
  in_flight: boolean;
  active_correlation_id?: string;
}
/**
 * PTT press from mobile. Hint to the orchestrator to begin the audio_stopped phase early. Not authoritative — the actual cancellation only happens once a transcript or user_text is received.
 */
export interface InterruptIntent {
  type: 'interrupt_intent';
}
/**
 * Overwatch-internal notification surfaced to the mobile UI. Mirrors the existing notification system.
 */
export interface Notification {
  type: 'notification';
  id: string;
  title: string;
  body: string;
  kind: string;
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Correlated error response. request_id echoes the originating envelope's id so the client can match.
 */
export interface ErrorResponse {
  type: 'error_response';
  request_id: string;
  error: {
    code: string;
    message: string;
  };
}

