// AUTO-GENERATED PROTOCOL TYPES — TS GENERATOR
//
// Reads /protocol/schema/*.schema.json and emits a single TS file at
// packages/shared/src/protocol/types.generated.ts.
//
// Run via: npm run protocol:gen:ts
//
// CI runs this and fails the build if the generated file drifts from the
// schemas. Never edit the output by hand — edit the schema and regenerate.

import { compileFromFile } from "json-schema-to-typescript";
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const schemaDir = join(repoRoot, "protocol", "schema");
const outFile = join(
  repoRoot,
  "packages",
  "shared",
  "src",
  "protocol",
  "types.generated.ts"
);

const banner = `// AUTO-GENERATED by scripts/codegen-ts.mjs from /protocol/schema/.
// DO NOT EDIT BY HAND. Edit the JSON Schema and run \`npm run protocol:gen\`.

/* eslint-disable */
/* tslint:disable */

`;

const files = readdirSync(schemaDir)
  .filter((f) => f.endsWith(".schema.json"))
  .sort();

let out = banner;

for (const file of files) {
  const compiled = await compileFromFile(join(schemaDir, file), {
    bannerComment: "",
    style: { semi: true, singleQuote: true, trailingComma: "es5" },
    additionalProperties: false,
  });
  out += `// ───────────────────── ${file} ─────────────────────\n\n${compiled}\n`;
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out, "utf8");
console.log(`Wrote ${outFile}`);
